table dim_doctor
	lineageTag: 4ce0e162-232d-4486-abea-7834541cf34b

	column doctor_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 37429c73-5d9f-417d-8f48-346348f56741
		summarizeBy: none
		sourceColumn: doctor_key

		annotation SummarizationSetBy = Automatic

	column doctor_id
		dataType: string
		lineageTag: b3a03947-b5a3-4f5f-a263-71cd67a7c696
		summarizeBy: none
		sourceColumn: doctor_id

		annotation SummarizationSetBy = Automatic

	column doctor_name
		dataType: string
		lineageTag: 4a75248c-596c-4fd4-90be-564de3caca49
		summarizeBy: none
		sourceColumn: doctor_name

		annotation SummarizationSetBy = Automatic

	column specialty
		dataType: string
		lineageTag: b9c73731-dfd2-4aa6-8f02-ff4958025a87
		summarizeBy: none
		sourceColumn: specialty

		annotation SummarizationSetBy = Automatic

	column years_experience
		dataType: int64
		formatString: 0
		lineageTag: 8c641942-2dba-4ae5-aca8-fff7944e7ed5
		summarizeBy: none
		sourceColumn: years_experience

		annotation SummarizationSetBy = Automatic

	column doctor_phone
		dataType: string
		isHidden
		lineageTag: ffe032b2-af13-4e96-a115-a92f867f42a6
		summarizeBy: none
		sourceColumn: doctor_phone

		annotation SummarizationSetBy = Automatic

	column employment_status
		dataType: string
		lineageTag: 5bcf2e22-6b9a-4e65-ae79-626058ce80e7
		summarizeBy: none
		sourceColumn: employment_status

		annotation SummarizationSetBy = Automatic

	column hospital_key
		dataType: int64
		formatString: 0
		lineageTag: e0263ce4-fba3-4592-8ebd-bfd154e10812
		summarizeBy: none
		sourceColumn: hospital_key

		annotation SummarizationSetBy = Automatic

	partition dim_doctor = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("dbc-687798f3-72ec.cloud.databricks.com", "/sql/1.0/warehouses/2eaa154934f93343", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    medical_insurance_Database = Source{[Name="medical_insurance",Kind="Database"]}[Data],
				    gold_Schema = medical_insurance_Database{[Name="gold",Kind="Schema"]}[Data],
				    dim_doctor_scd2_Table = gold_Schema{[Name="dim_doctor_scd2",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dim_doctor_scd2_Table,{"scd_start_date", "scd_end_date", "scd_is_current", "scd_version", "dwh_created_at", "dwh_updated_at", "department_key"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

