table dim_patient
	lineageTag: 6dc2d356-ea87-45b6-9be9-1b8c276f7dc8

	column patient_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e77b94af-6a42-4956-90ff-9a51a394cb80
		summarizeBy: none
		sourceColumn: patient_key

		annotation SummarizationSetBy = Automatic

	column patient_id
		dataType: string
		lineageTag: f50afd86-ff96-4ab9-b10e-39d4ccc704e8
		summarizeBy: none
		sourceColumn: patient_id

		annotation SummarizationSetBy = Automatic

	column national_id
		dataType: string
		isHidden
		lineageTag: 0e5cb1c5-c173-4e61-83eb-b24e1ec2e995
		summarizeBy: none
		sourceColumn: national_id

		annotation SummarizationSetBy = Automatic

	column patient_name
		dataType: string
		lineageTag: 6e3afce4-3aca-4d15-9ba0-67dbcc1c03ad
		summarizeBy: none
		sourceColumn: patient_name

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: f7702df5-34d1-4da9-b36c-0e03aa4f0f61
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column birth_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a786f57a-35e5-46fb-9365-8d051e54633f
		summarizeBy: none
		sourceColumn: birth_date

		variation Variation
			isDefault
			relationship: 19a269d1-1c52-4d13-bfe8-d54c43e4c374
			defaultHierarchy: LocalDateTable_88088965-c040-4725-89b4-d3eb98ed9bfc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column age_group
		dataType: string
		lineageTag: e8596f83-d771-4a61-8f4b-a641eeef23ee
		summarizeBy: none
		sourceColumn: age_group

		annotation SummarizationSetBy = Automatic

	column patient_phone
		dataType: string
		isHidden
		lineageTag: 79ab3352-a444-4401-8b42-2e43e86abf7f
		summarizeBy: none
		sourceColumn: patient_phone

		annotation SummarizationSetBy = Automatic

	column street
		dataType: string
		lineageTag: 218460fa-2943-4a84-8d22-8c909076450b
		summarizeBy: none
		sourceColumn: street

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 21ce6044-e789-40b6-b782-0071304972ac
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column governorate
		dataType: string
		lineageTag: 4bf7e948-7dd0-42cd-91c1-b67c5b4e2b6c
		summarizeBy: none
		sourceColumn: governorate

		annotation SummarizationSetBy = Automatic

	column blood_type
		dataType: string
		lineageTag: d0b63c67-a19c-4aea-b533-3bd1b1f0552a
		summarizeBy: none
		sourceColumn: blood_type

		annotation SummarizationSetBy = Automatic

	column emergency_contact
		dataType: string
		isHidden
		lineageTag: bcaf3e74-099c-4c98-b816-a89e347815cd
		summarizeBy: none
		sourceColumn: emergency_contact

		annotation SummarizationSetBy = Automatic

	column Age =
			
			DATEDIFF(
			    dim_patient[birth_date],
			    TODAY(),
			    YEAR
			)
		formatString: 0
		lineageTag: b9616536-d863-4d64-bd5f-8c3478ea4b52
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition dim_patient = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("dbc-687798f3-72ec.cloud.databricks.com", "/sql/1.0/warehouses/2eaa154934f93343", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    medical_insurance_Database = Source{[Name="medical_insurance",Kind="Database"]}[Data],
				    gold_Schema = medical_insurance_Database{[Name="gold",Kind="Schema"]}[Data],
				    dim_patient_scd2_Table = gold_Schema{[Name="dim_patient_scd2",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dim_patient_scd2_Table,{"scd_start_date", "scd_end_date", "scd_is_current", "scd_version", "dwh_created_at", "dwh_updated_at"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

