table dim_date
	lineageTag: 4fbc4202-3b35-48ad-a5bb-56d649893afb
	dataCategory: Time

	column date_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 871cf298-fcbe-44ca-9ee8-32845af8a855
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 300b82b5-80dc-482c-b345-d37a32c7fbf8
		summarizeBy: none
		sourceColumn: full_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 1d848470-6bb4-4944-9431-f14074073db7
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: d93c570e-ec41-474e-ac0e-b76475955ad0
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 0ddbbd3e-4880-4c05-a1be-a5de9b439bd2
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: dda0cdca-35c9-4d08-9f98-3ae8990e1bb4
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column week
		dataType: int64
		formatString: 0
		lineageTag: 5bc20c77-55e1-42ba-95b1-49ecce6f40e3
		summarizeBy: none
		sourceColumn: week

		annotation SummarizationSetBy = Automatic

	column day_of_month
		dataType: int64
		formatString: 0
		lineageTag: 05b0d27f-c7f0-4921-9649-145bba41834e
		summarizeBy: none
		sourceColumn: day_of_month

		annotation SummarizationSetBy = User

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: b6fa33b8-a43b-4ebf-9827-74421306abee
		summarizeBy: none
		sourceColumn: day_of_week

		annotation SummarizationSetBy = User

	column day_name
		dataType: string
		lineageTag: dd907d0f-9f34-4435-ba8d-19aaacaefba9
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 09b0105d-6cec-4e4b-9141-425da91b0d95
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column season
		dataType: string
		lineageTag: 62c159fd-6f4a-439c-b8ae-517aae55ce4d
		summarizeBy: none
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4bb4a8a1-a30b-47d9-ab78-c7754be818b0

		level year
			lineageTag: 4e1d9bcf-56f4-4572-ab05-e6883ef98ada
			column: year

		level quarter
			lineageTag: dd1865ad-bb77-4c40-b2b6-9cae8c4da93b
			column: quarter

		level month_name
			lineageTag: 8dd75b7b-1b80-4fb5-90cb-fa97c47c2511
			column: month_name

		level day_name
			lineageTag: 2749ca28-87e8-4023-9d60-f143c01939d9
			column: day_name

	partition dim_date = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("dbc-687798f3-72ec.cloud.databricks.com", "/sql/1.0/warehouses/2eaa154934f93343", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    medical_insurance_Database = Source{[Name="medical_insurance",Kind="Database"]}[Data],
				    gold_Schema = medical_insurance_Database{[Name="gold",Kind="Schema"]}[Data],
				    dim_date_scd1_Table = gold_Schema{[Name="dim_date_scd1",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dim_date_scd1_Table,{"dwh_created_at", "dwh_updated_at"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

